//GET CATEGORIES
export const GET_CATEGORIES = 'GET_CATEGORIES';

//GET EVENT BY CATEGORY
export const GET_EVENTCATEGORIES = 'GET_EVENTCATEGORIES';

//POST User
// export const POST_USER = 'POST_USER';

//GET EVENT TODAY
export const GET_EVENT = 'GET_EVENT';

//GET EVENT TOMOROW
export const GET_NEXTEVENT = 'GET_NEXTEVENT';

//LOGIN lOG OUT REQUEST
