//GET CATEGORIES
export const GET_CATEGORIES = 'GET_CATEGORIES';

//GET EVENT BY CATEGORY
export const GET_EVENTCATEGORIES = 'GET_EVENTCATEGORIES';

//GET FAVORITE EVENT BY USER
export const GET_FAVORITE = 'GET_FAVORITE';

//GET EVENT TODAY
export const GET_EVENT = 'GET_EVENT';

//GET EVENT TOMOROW
export const GET_NEXTEVENT = 'GET_NEXTEVENT';

//GET USER
export const GET_PROFILE = 'GET_PROFILE';

//GET DETAIL EVENT
export const GET_DETAILEVENT = 'GET_DETAILEVENT';
